### PR TITLE
feat: removed conditional to allow forum cmds

### PR DESCRIPTION
**Pull request by gitfitbro**
@borolepratik @vongarcia97 this is a simple change that is preventing us from creating support tickets in a forum post

### CODE REVIEW

**Comment by borolepratik** [comment]
@gitfitbro how was this tested if you werent able to create forums in digital junkyard?

**Review by borolepratik — CHANGES_REQUESTED** [review]
@gitfitbro this is a destructive change with side effects. please ensure to keep the current logic of not being able to create threads inside threads intact.

**Comment by borolepratik** [comment]
and please dont raise a PR without testing your own changes first.

**Comment by gitfitbro** [comment]
@borolepratik its now a draft PR :)

**Comment by gitfitbro** [comment]
@borolepratik at least with my code changes, I think it would be better if we pair code when doing code review. I think it will allow us to get things done faster and share context a lot faster. Are you down for that?

**Comment by borolepratik** [comment]
ya doing code reviews together is doable for me, but would love the road leading to the PR to be smooth :)

**Comment by borolepratik** [comment]
PR closed; re-open a new one when ready!

**Pull request closed without merging**
